//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Test
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Вид.
    /// </summary>
    // *** Start programmer edit section *** (Вид CustomAttributes)

    // *** End programmer edit section *** (Вид CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ВидE", new string[] {
            "Наименование as \'Наименование\'"})]
    [View("ВидL", new string[] {
            "Наименование as \'Наименование\'"})]
    public class Вид : ICSSoft.STORMNET.DataObject
    {
        
        private string fНаименование;
        
        // *** Start programmer edit section *** (Вид CustomMembers)

        // *** End programmer edit section *** (Вид CustomMembers)

        
        /// <summary>
        /// Наименование.
        /// </summary>
        // *** Start programmer edit section *** (Вид.Наименование CustomAttributes)

        // *** End programmer edit section *** (Вид.Наименование CustomAttributes)
        [StrLen(255)]
        public virtual string Наименование
        {
            get
            {
                // *** Start programmer edit section *** (Вид.Наименование Get start)

                // *** End programmer edit section *** (Вид.Наименование Get start)
                string result = this.fНаименование;
                // *** Start programmer edit section *** (Вид.Наименование Get end)

                // *** End programmer edit section *** (Вид.Наименование Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Вид.Наименование Set start)

                // *** End programmer edit section *** (Вид.Наименование Set start)
                this.fНаименование = value;
                // *** Start programmer edit section *** (Вид.Наименование Set end)

                // *** End programmer edit section *** (Вид.Наименование Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ВидE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ВидE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ВидE", typeof(IIS.Test.Вид));
                }
            }
            
            /// <summary>
            /// "ВидL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ВидL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ВидL", typeof(IIS.Test.Вид));
                }
            }
        }
    }
}
