//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Test
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Корма.
    /// </summary>
    // *** Start programmer edit section *** (Корма CustomAttributes)

    // *** End programmer edit section *** (Корма CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("КормаE", new string[] {
            "ТипКорма as \'Тип корма\'",
            "НомерЖивотного as \'Номер животного\'"})]
    [View("КормаL", new string[] {
            "ТипКорма as \'Тип корма\'",
            "НомерЖивотного as \'Номер животного\'"})]
    public class Корма : ICSSoft.STORMNET.DataObject
    {
        
        private string fТипКорма;
        
        private int fНомерЖивотного;
        
        // *** Start programmer edit section *** (Корма CustomMembers)

        // *** End programmer edit section *** (Корма CustomMembers)

        
        /// <summary>
        /// НомерЖивотного.
        /// </summary>
        // *** Start programmer edit section *** (Корма.НомерЖивотного CustomAttributes)

        // *** End programmer edit section *** (Корма.НомерЖивотного CustomAttributes)
        public virtual int НомерЖивотного
        {
            get
            {
                // *** Start programmer edit section *** (Корма.НомерЖивотного Get start)

                // *** End programmer edit section *** (Корма.НомерЖивотного Get start)
                int result = this.fНомерЖивотного;
                // *** Start programmer edit section *** (Корма.НомерЖивотного Get end)

                // *** End programmer edit section *** (Корма.НомерЖивотного Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Корма.НомерЖивотного Set start)

                // *** End programmer edit section *** (Корма.НомерЖивотного Set start)
                this.fНомерЖивотного = value;
                // *** Start programmer edit section *** (Корма.НомерЖивотного Set end)

                // *** End programmer edit section *** (Корма.НомерЖивотного Set end)
            }
        }
        
        /// <summary>
        /// ТипКорма.
        /// </summary>
        // *** Start programmer edit section *** (Корма.ТипКорма CustomAttributes)

        // *** End programmer edit section *** (Корма.ТипКорма CustomAttributes)
        [StrLen(255)]
        public virtual string ТипКорма
        {
            get
            {
                // *** Start programmer edit section *** (Корма.ТипКорма Get start)

                // *** End programmer edit section *** (Корма.ТипКорма Get start)
                string result = this.fТипКорма;
                // *** Start programmer edit section *** (Корма.ТипКорма Get end)

                // *** End programmer edit section *** (Корма.ТипКорма Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Корма.ТипКорма Set start)

                // *** End programmer edit section *** (Корма.ТипКорма Set start)
                this.fТипКорма = value;
                // *** Start programmer edit section *** (Корма.ТипКорма Set end)

                // *** End programmer edit section *** (Корма.ТипКорма Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "КормаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КормаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КормаE", typeof(IIS.Test.Корма));
                }
            }
            
            /// <summary>
            /// "КормаL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КормаL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КормаL", typeof(IIS.Test.Корма));
                }
            }
        }
    }
}
