//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Test
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Расписание корм.
    /// </summary>
    // *** Start programmer edit section *** (РасписаниеКорм CustomAttributes)

    // *** End programmer edit section *** (РасписаниеКорм CustomAttributes)
    [AutoAltered()]
    [Caption("Расписание корм")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("РасписаниеКормE", new string[] {
            "Время as \'Время\'",
            "Животные as \'Животные\'",
            "Животные.Сотрудники.ТабличНомер as \'Табельный номер\'",
            "Животные.КодВида as \'Код вида\'"}, Hidden=new string[] {
            "Животные.КодВида"})]
    [MasterViewDefineAttribute("РасписаниеКормE", "Животные", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "КодВида")]
    [View("РасписаниеКормL", new string[] {
            "Время as \'Время\'",
            "Животные.КодВида as \'Код вида\'"})]
    public class РасписаниеКорм : ICSSoft.STORMNET.DataObject
    {
        
        private string fВремя;
        
        private IIS.Test.Животные fЖивотные;
        
        // *** Start programmer edit section *** (РасписаниеКорм CustomMembers)

        // *** End programmer edit section *** (РасписаниеКорм CustomMembers)

        
        /// <summary>
        /// Время.
        /// </summary>
        // *** Start programmer edit section *** (РасписаниеКорм.Время CustomAttributes)

        // *** End programmer edit section *** (РасписаниеКорм.Время CustomAttributes)
        [StrLen(255)]
        public virtual string Время
        {
            get
            {
                // *** Start programmer edit section *** (РасписаниеКорм.Время Get start)

                // *** End programmer edit section *** (РасписаниеКорм.Время Get start)
                string result = this.fВремя;
                // *** Start programmer edit section *** (РасписаниеКорм.Время Get end)

                // *** End programmer edit section *** (РасписаниеКорм.Время Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (РасписаниеКорм.Время Set start)

                // *** End programmer edit section *** (РасписаниеКорм.Время Set start)
                this.fВремя = value;
                // *** Start programmer edit section *** (РасписаниеКорм.Время Set end)

                // *** End programmer edit section *** (РасписаниеКорм.Время Set end)
            }
        }
        
        /// <summary>
        /// Расписание корм.
        /// </summary>
        // *** Start programmer edit section *** (РасписаниеКорм.Животные CustomAttributes)

        // *** End programmer edit section *** (РасписаниеКорм.Животные CustomAttributes)
        [PropertyStorage(new string[] {
                "Животные"})]
        [NotNull()]
        public virtual IIS.Test.Животные Животные
        {
            get
            {
                // *** Start programmer edit section *** (РасписаниеКорм.Животные Get start)

                // *** End programmer edit section *** (РасписаниеКорм.Животные Get start)
                IIS.Test.Животные result = this.fЖивотные;
                // *** Start programmer edit section *** (РасписаниеКорм.Животные Get end)

                // *** End programmer edit section *** (РасписаниеКорм.Животные Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (РасписаниеКорм.Животные Set start)

                // *** End programmer edit section *** (РасписаниеКорм.Животные Set start)
                this.fЖивотные = value;
                // *** Start programmer edit section *** (РасписаниеКорм.Животные Set end)

                // *** End programmer edit section *** (РасписаниеКорм.Животные Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "РасписаниеКормE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View РасписаниеКормE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("РасписаниеКормE", typeof(IIS.Test.РасписаниеКорм));
                }
            }
            
            /// <summary>
            /// "РасписаниеКормL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View РасписаниеКормL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("РасписаниеКормL", typeof(IIS.Test.РасписаниеКорм));
                }
            }
        }
    }
}
