//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Test
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Сведения.
    /// </summary>
    // *** Start programmer edit section *** (Сведения CustomAttributes)

    // *** End programmer edit section *** (Сведения CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("СведенияE", new string[] {
            "Код as \'Код\'",
            "Кличка as \'Кличка\'",
            "Корма as \'Корма\'",
            "Корма.ТипКорма as \'Тип корма\'",
            "Вид as \'Вид\'",
            "Вид.Наименование as \'Наименование\'",
            "Клетки as \'Клетки\'",
            "Клетки.НомерКлетки as \'Номер клетки\'",
            "Клетки.ТипКлетки as \'Тип клетки\'"}, Hidden=new string[] {
            "Корма.ТипКорма",
            "Вид.Наименование",
            "Клетки.ТипКлетки"})]
    [MasterViewDefineAttribute("СведенияE", "Корма", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ТипКорма")]
    [MasterViewDefineAttribute("СведенияE", "Вид", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Наименование")]
    [MasterViewDefineAttribute("СведенияE", "Клетки", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ТипКлетки")]
    public class Сведения : ICSSoft.STORMNET.DataObject
    {
        
        private int fКод;
        
        private string fКличка;
        
        private IIS.Test.Корма fКорма;
        
        private IIS.Test.Вид fВид;
        
        private IIS.Test.Клетки fКлетки;
        
        private IIS.Test.Животные fЖивотные;
        
        // *** Start programmer edit section *** (Сведения CustomMembers)

        // *** End programmer edit section *** (Сведения CustomMembers)

        
        /// <summary>
        /// Кличка.
        /// </summary>
        // *** Start programmer edit section *** (Сведения.Кличка CustomAttributes)

        // *** End programmer edit section *** (Сведения.Кличка CustomAttributes)
        [StrLen(255)]
        public virtual string Кличка
        {
            get
            {
                // *** Start programmer edit section *** (Сведения.Кличка Get start)

                // *** End programmer edit section *** (Сведения.Кличка Get start)
                string result = this.fКличка;
                // *** Start programmer edit section *** (Сведения.Кличка Get end)

                // *** End programmer edit section *** (Сведения.Кличка Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сведения.Кличка Set start)

                // *** End programmer edit section *** (Сведения.Кличка Set start)
                this.fКличка = value;
                // *** Start programmer edit section *** (Сведения.Кличка Set end)

                // *** End programmer edit section *** (Сведения.Кличка Set end)
            }
        }
        
        /// <summary>
        /// Код.
        /// </summary>
        // *** Start programmer edit section *** (Сведения.Код CustomAttributes)

        // *** End programmer edit section *** (Сведения.Код CustomAttributes)
        public virtual int Код
        {
            get
            {
                // *** Start programmer edit section *** (Сведения.Код Get start)

                // *** End programmer edit section *** (Сведения.Код Get start)
                int result = this.fКод;
                // *** Start programmer edit section *** (Сведения.Код Get end)

                // *** End programmer edit section *** (Сведения.Код Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сведения.Код Set start)

                // *** End programmer edit section *** (Сведения.Код Set start)
                this.fКод = value;
                // *** Start programmer edit section *** (Сведения.Код Set end)

                // *** End programmer edit section *** (Сведения.Код Set end)
            }
        }
        
        /// <summary>
        /// Сведения.
        /// </summary>
        // *** Start programmer edit section *** (Сведения.Вид CustomAttributes)

        // *** End programmer edit section *** (Сведения.Вид CustomAttributes)
        [PropertyStorage(new string[] {
                "Вид"})]
        [NotNull()]
        public virtual IIS.Test.Вид Вид
        {
            get
            {
                // *** Start programmer edit section *** (Сведения.Вид Get start)

                // *** End programmer edit section *** (Сведения.Вид Get start)
                IIS.Test.Вид result = this.fВид;
                // *** Start programmer edit section *** (Сведения.Вид Get end)

                // *** End programmer edit section *** (Сведения.Вид Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сведения.Вид Set start)

                // *** End programmer edit section *** (Сведения.Вид Set start)
                this.fВид = value;
                // *** Start programmer edit section *** (Сведения.Вид Set end)

                // *** End programmer edit section *** (Сведения.Вид Set end)
            }
        }
        
        /// <summary>
        /// Сведения.
        /// </summary>
        // *** Start programmer edit section *** (Сведения.Клетки CustomAttributes)

        // *** End programmer edit section *** (Сведения.Клетки CustomAttributes)
        [PropertyStorage(new string[] {
                "Клетки"})]
        [NotNull()]
        public virtual IIS.Test.Клетки Клетки
        {
            get
            {
                // *** Start programmer edit section *** (Сведения.Клетки Get start)

                // *** End programmer edit section *** (Сведения.Клетки Get start)
                IIS.Test.Клетки result = this.fКлетки;
                // *** Start programmer edit section *** (Сведения.Клетки Get end)

                // *** End programmer edit section *** (Сведения.Клетки Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сведения.Клетки Set start)

                // *** End programmer edit section *** (Сведения.Клетки Set start)
                this.fКлетки = value;
                // *** Start programmer edit section *** (Сведения.Клетки Set end)

                // *** End programmer edit section *** (Сведения.Клетки Set end)
            }
        }
        
        /// <summary>
        /// Сведения.
        /// </summary>
        // *** Start programmer edit section *** (Сведения.Корма CustomAttributes)

        // *** End programmer edit section *** (Сведения.Корма CustomAttributes)
        [PropertyStorage(new string[] {
                "Корма"})]
        [NotNull()]
        public virtual IIS.Test.Корма Корма
        {
            get
            {
                // *** Start programmer edit section *** (Сведения.Корма Get start)

                // *** End programmer edit section *** (Сведения.Корма Get start)
                IIS.Test.Корма result = this.fКорма;
                // *** Start programmer edit section *** (Сведения.Корма Get end)

                // *** End programmer edit section *** (Сведения.Корма Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сведения.Корма Set start)

                // *** End programmer edit section *** (Сведения.Корма Set start)
                this.fКорма = value;
                // *** Start programmer edit section *** (Сведения.Корма Set end)

                // *** End programmer edit section *** (Сведения.Корма Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Test.Животные.
        /// </summary>
        // *** Start programmer edit section *** (Сведения.Животные CustomAttributes)

        // *** End programmer edit section *** (Сведения.Животные CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "Животные"})]
        public virtual IIS.Test.Животные Животные
        {
            get
            {
                // *** Start programmer edit section *** (Сведения.Животные Get start)

                // *** End programmer edit section *** (Сведения.Животные Get start)
                IIS.Test.Животные result = this.fЖивотные;
                // *** Start programmer edit section *** (Сведения.Животные Get end)

                // *** End programmer edit section *** (Сведения.Животные Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сведения.Животные Set start)

                // *** End programmer edit section *** (Сведения.Животные Set start)
                this.fЖивотные = value;
                // *** Start programmer edit section *** (Сведения.Животные Set end)

                // *** End programmer edit section *** (Сведения.Животные Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "СведенияE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СведенияE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СведенияE", typeof(IIS.Test.Сведения));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of Сведения.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfСведения CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfСведения CustomAttributes)
    public class DetailArrayOfСведения : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Test.DetailArrayOfСведения members)

        // *** End programmer edit section *** (IIS.Test.DetailArrayOfСведения members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type Сведения by index.
        /// </summary>
        /// <summary>
        /// Adds object with type Сведения.
        /// </summary>
        public DetailArrayOfСведения(IIS.Test.Животные fЖивотные) : 
                base(typeof(Сведения), ((ICSSoft.STORMNET.DataObject)(fЖивотные)))
        {
        }
        
        public IIS.Test.Сведения this[int index]
        {
            get
            {
                return ((IIS.Test.Сведения)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Test.Сведения dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
